version: 2

updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  target-branch: develop

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  target-branch: develop
  reviewers:
  - maxlutz98

- package-ecosystem: pipenv
  directory: "/project"
  schedule:
    interval: weekly
  target-branch: develop
  reviewers:
  - maxlutz98
