version: "3.7"

services:
  django:
    image: "fantasmas/friendscal:${BRANCH}"
    restart: always
    expose:
      - "8000"
    volumes:
      - media:/code/media
      - staticfiles:/code/staticfiles
    command: gunicorn -w 3 djangoproject.wsgi:application --bind 0.0.0.0:8000
    networks:
      - django-network
    env_file: example-django.env
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    restart: always
    networks:
      - django-network
    env_file: example-db.env

  nginx:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/code/staticfiles
      - media:/code/media
    networks:
      - django-network
    depends_on:
      - django

volumes:
  media:
  staticfiles:

networks:
  django-network:
    driver: bridge