version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
    - ./db:/var/lib/mysql
    networks:
    - django-network
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: VM^r7m63tDkqGH4@
      MYSQL_DATABASE: django_db
      MYSQL_USER: djangouser
      MYSQL_PASSWORD: pw4djangouser
    labels: 
      - "traefik.enable=false"

  web:
    build: build
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./project:/code
    command: python manage.py runserver 0.0.0.0:8000
    networks:
    - django-network
    depends_on:
      - db
    labels: 
      - "traefik.enable=true"
      - "traefik.backend=django"
      - "traefik.port=8000"
#      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=PathPrefixStrip:/cal"
      - "traefik.docker.network=django-network"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.redirect.regex=^(.*)/cal$$"
      - "traefik.frontend.redirect.replacement=$$1/cal/"
      - "traefik.frontend.rule=PathPrefix:/cal;ReplacePathRegex: ^/cal/(.*) /$$1"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - django-network
    labels: 
      - "traefik.enable=true"
      - "traefik.backend=phpmyadmin"
      - "traefik.port=8080"
#      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=PathPrefixStrip:/phpmyadmin"
      - "traefik.docker.network=django-network"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.redirect.regex=^(.*)/phpmyadmin$$"
      - "traefik.frontend.redirect.replacement=$$1/phpmyadmin/"
      - "traefik.frontend.rule=PathPrefix:/phpmyadmin;ReplacePathRegex: ^/phpmyadmin/(.*) /$$1"
  
  sass-watcher:
    build: sass-container
    restart: always
    volumes:
    - ./sass:/sass



networks:
  django-network:
    driver: bridge