version: "3.7"

services:
  django:
    build: django-container
    restart: always
    expose:
      - "8000"
    volumes:
      - ./project:/code
    command: gunicorn -w 3 djangoproject.wsgi:application --bind 0.0.0.0:8000
    networks:
      - django-network
    env_file: django.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - django-network
    env_file: db.env

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./project/staticfiles:/code/staticfiles
      - ./project/media:/code/media
    networks:
      - django-network
    depends_on:
      - django

networks:
  django-network:
    driver: bridge
