# Generated by Django 2.2.1 on 2019-06-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendscal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetail',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share_id',
            new_name='share',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='to_user_id',
            new_name='to_user',
        ),
    ]
