# Generated by Django 2.2.5 on 2019-09-05 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share',
            field=models.ManyToManyField(blank=True, help_text='Nutzer, die deinen Kalender einsehen dürfen.', to=settings.AUTH_USER_MODEL, verbose_name='Freigaben'),
        ),
    ]
