# Generated by Django 2.2.2 on 2019-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190703_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default-profile.jpg', upload_to='avatars', verbose_name='profile picture'),
        ),
    ]
