# Generated by Django 2.2.5 on 2019-09-06 10:06

from django.db import migrations

def gen_username(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for row in User.objects.all():
        row.username = row.first_name + row.last_name
        row.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.RunPython(gen_username, reverse_code=migrations.RunPython.noop),
    ]
