# Generated by Django 2.2.5 on 2019-09-06 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190906_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='share',
        ),
        migrations.AddField(
            model_name='user',
            name='invitations',
            field=models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user',
            name='shares',
            field=models.ManyToManyField(blank=True, help_text='Nutzer, die deinen Kalender einsehen dürfen.', related_name='shared_by', to=settings.AUTH_USER_MODEL, verbose_name='Freigaben'),
        ),
    ]
