# Generated by Django 2.2.5 on 2019-09-07 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190906_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Nur Buchstaben, Zahlen und @/./+/-/_ .', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Gib einen gültigen Nutzernamen ein.', 'invalid')], verbose_name='Nutzername'),
        ),
    ]
