name: Deploy Docker Image on Push

on: [push]

jobs:
  build_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fantasmas/friendscal
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  smoketest:
    name: Smoketest the built container
    needs: [build_push]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Log into Docker registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Logged in"
    - name: Set up docker environment
      run: |
        BRANCH=$(echo "${GITHUB_REF}" | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")
        if [ "${BRANCH}" = "master" ] 
          then BRANCH="latest"
        fi 
        export BRANCH=${BRANCH}
        echo "${BRANCH}"
        docker-compose -f "docker-compose.test.yml" up -d --build
    - name: Check accessibility
      run: |
        sleep 10s
        curl -f localhost:8080
    - name: Cleanup
      run: |
        docker-compose -f "docker-compose.test.yml" down
        docker logout
