name: Smoketest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into Docker registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Logged in"
    - name: Set up docker environment
      run: |
        BRANCH=$(echo "${GITHUB_REF}" | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")
        if [ "${BRANCH}" = "master" ] 
          then BRANCH="latest"
        fi 
        export BRANCH=${BRANCH}
        echo "${BRANCH}"
        docker-compose -f "docker-compose.test.yml" up -d --build
    - name: Check accessibility
      run: |
        sleep 10s
        curl -f localhost:8080